### ISSUE TITLE
`scheduler` is undefined

### ISSUE THREAD

**Issue by MyTotoro** [fastify/fastify-schedule#11]
## 🐛 Bug Report

Can't access `schedule` object

## To Reproduce

See attachments

## Expected behavior

I expect it to work

## Your Environment

- *node version*: 14.16.0
- *fastify version*: >= 3.14.2
- *fastify schedule v*: >= 1.0.0
- *os*: Linux
- *any other relevant information*
- 
![5](https://user-images.githubusercontent.com/3621921/115578957-b83f9900-a293-11eb-94c0-fbc86ca6d4fb.PNG)
![6](https://user-images.githubusercontent.com/3621921/115578959-b8d82f80-a293-11eb-8e67-21af73bc61bd.png)

**Comment by kibertoad** [comment]
I'll take a look now

**Comment by kibertoad** [comment]
Could you please paste mentioned code as a code and not a picture, so that I could repro easier?

**Comment by MyTotoro** [comment]
Sure thing, this was all copy and paste from documentation
```'use strict'
const { fastifySchedulePlugin } = require('fastify-schedule')
const { SimpleIntervalJob, AsyncTask } = require('toad-scheduler')

const fastify = require('fastify')({
  logger: true
})

fastify.register(fastifySchedulePlugin);

const task = new AsyncTask(
    'simple task',
    () => { new Promise((resolve, reject) => {
      console.log("in simple task")
      resolve()}).then((result) => { /* continue the promise chain */ }) },
    (err) => { /* handle errors here */ }
)
const job = new SimpleIntervalJob({ seconds: 20, }, task)

fastify.scheduler.addSimpleIntervalJob(job)

// fastify.register(require('./our-first-route'))

// Run the server!
fastify.listen(9000, '0.0.0.0', function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})```

**Comment by kibertoad** [comment]
@MyTotoro I think we need to clarify documentation here. What is happening is that plugin is not yet initialized, you can only start registering tasks after calling `await fastify.ready();`.
Sorry for the confusion.

**Comment by MyTotoro** [comment]
Cool, seems like adding works

```
fastify.ready().then(() => {
  console.log('fastify.ready(), successfully booted!')
  
  fastify.scheduler.addSimpleIntervalJob(job)
  
}, (err) => {
  console.log('an error happened', err)
})
```
