### ISSUE TITLE
The latest version on npm not match fastify 5.0.0 

### ISSUE THREAD

**Issue by azhezzzz** [fastify/fastify-schedule#141]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Plugin version

5.0.0

### Node.js version

20.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.1.1

### Description

The peerDependencies of the latest version on npm still use "fastify": "^4.0.0" and not match fastify 5.0.0 
https://www.npmjs.com/package/@fastify/schedule?activeTab=code
<img width="869" alt="image" src="https://github.com/user-attachments/assets/8142f5c6-c0dc-4ae9-967a-55e8773875e3">

and it cause the npm install error

<img width="726" alt="image" src="https://github.com/user-attachments/assets/e85a2291-9af9-4af1-a8c3-d4ba50caecaf">

### Expected Behavior

Update the latest version on npm to match the fastify 5.0.0

**Comment by gurgunday** [comment]
Thanks for reporting!

Closed by https://github.com/fastify/fastify-schedule/releases/tag/v5.0.1
